import type { Metadata } from "next";
import { Nunito, Montserrat } from "next/font/google";
import "@/shared/styles/base/normalize.scss";
import "@/shared/styles/base/globals.scss";
import { QueryRouter } from "./routers/QueryRouter";

const NunitoSans = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"]
});

const MontserratSans = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "F.palace",
  description: "Generated by create next app",
  authors: {
    name: "BlackDarkes(DaniilGordeev)"
  },
  icons: {
    icon: "/favicon.svg",
    shortcut: "/favicon.svg"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${NunitoSans.variable} ${MontserratSans.variable}`}>
        <QueryRouter>
          { children }
        </QueryRouter>
      </body>
    </html>
  );
}
